# Generated by Django 6.0.1 on 2026-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_resume_id_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_level',
            field=models.CharField(default='Fresher', max_length=50),
        ),
    ]
