# Generated by Django 6.0.1 on 2026-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='improvements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='strengths',
            field=models.JSONField(default=list),
        ),
    ]
