# Generated by Django 6.0.1 on 2026-05-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_improvements_resume_resume_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(default=list),
        ),
    ]
