# Generated by Django 6.0.1 on 2026-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_ai_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='career_paths',
            field=models.JSONField(default=list),
        ),
    ]
