# Generated by Django 5.2.7 on 2026-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma separated skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
